/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package es.cajal.autocodigo.forms;

import es.cajal.autocodigo.Contenedor;
import es.cajal.autocodigo.generacion.GeneracionBd;
import es.cajal.autocodigo.generacion.GeneracionRegistro;
import es.cajal.autocodigo.generacion.GeneracionUtilidad;
import java.awt.Toolkit;
import java.awt.datatransfer.Clipboard;
import java.awt.datatransfer.StringSelection;

/**
 *
 * @author pmpreciado
 */
public class FormGenerarCodigo extends javax.swing.JFrame {

    private static final int TAB_ACCESO_BD              = 0;
    private static final int TAB_CLASE_REGISTRO         = 1;
    private static final int TAB_CLASE_UTILIDAD         = 2;
    
    
    /** Referencia al objeto contenedor */
    Contenedor cnt;
    
    
    /**
     * Creates new form FormGenerarCodigo
     * 
     * @param cnt                               Objeto contenedor
     */
    public FormGenerarCodigo(Contenedor cnt) {
        this.cnt = cnt;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tabbedPanelCodigoGenerado = new javax.swing.JTabbedPane();
        panelAccesoBd = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        taAccesoBd = new javax.swing.JTextArea();
        panelClaseRegistro = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        taAccesoRegistro = new javax.swing.JTextArea();
        panelClaseUtil = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        taClaseUtilidad = new javax.swing.JTextArea();
        btnCerrar = new javax.swing.JButton();
        btnCopiar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Código generado");

        taAccesoBd.setBackground(new java.awt.Color(226, 226, 226));
        taAccesoBd.setColumns(20);
        taAccesoBd.setFont(new java.awt.Font("Lucida Sans Typewriter", 0, 10)); // NOI18N
        taAccesoBd.setRows(5);
        jScrollPane1.setViewportView(taAccesoBd);

        javax.swing.GroupLayout panelAccesoBdLayout = new javax.swing.GroupLayout(panelAccesoBd);
        panelAccesoBd.setLayout(panelAccesoBdLayout);
        panelAccesoBdLayout.setHorizontalGroup(
            panelAccesoBdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAccesoBdLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 981, Short.MAX_VALUE)
                .addContainerGap())
        );
        panelAccesoBdLayout.setVerticalGroup(
            panelAccesoBdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAccesoBdLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 438, Short.MAX_VALUE)
                .addContainerGap())
        );

        tabbedPanelCodigoGenerado.addTab("Acceso a la base de datos", panelAccesoBd);

        taAccesoRegistro.setBackground(new java.awt.Color(226, 226, 226));
        taAccesoRegistro.setColumns(20);
        taAccesoRegistro.setFont(new java.awt.Font("Lucida Sans Typewriter", 0, 10)); // NOI18N
        taAccesoRegistro.setRows(5);
        jScrollPane2.setViewportView(taAccesoRegistro);

        javax.swing.GroupLayout panelClaseRegistroLayout = new javax.swing.GroupLayout(panelClaseRegistro);
        panelClaseRegistro.setLayout(panelClaseRegistroLayout);
        panelClaseRegistroLayout.setHorizontalGroup(
            panelClaseRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelClaseRegistroLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 981, Short.MAX_VALUE)
                .addContainerGap())
        );
        panelClaseRegistroLayout.setVerticalGroup(
            panelClaseRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelClaseRegistroLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 438, Short.MAX_VALUE)
                .addContainerGap())
        );

        tabbedPanelCodigoGenerado.addTab("Clase para el registro", panelClaseRegistro);

        taClaseUtilidad.setBackground(new java.awt.Color(226, 226, 226));
        taClaseUtilidad.setColumns(20);
        taClaseUtilidad.setFont(new java.awt.Font("Lucida Sans Typewriter", 0, 10)); // NOI18N
        taClaseUtilidad.setRows(5);
        jScrollPane3.setViewportView(taClaseUtilidad);

        javax.swing.GroupLayout panelClaseUtilLayout = new javax.swing.GroupLayout(panelClaseUtil);
        panelClaseUtil.setLayout(panelClaseUtilLayout);
        panelClaseUtilLayout.setHorizontalGroup(
            panelClaseUtilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelClaseUtilLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 981, Short.MAX_VALUE)
                .addContainerGap())
        );
        panelClaseUtilLayout.setVerticalGroup(
            panelClaseUtilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelClaseUtilLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 438, Short.MAX_VALUE)
                .addContainerGap())
        );

        tabbedPanelCodigoGenerado.addTab("Clase de utilidad", panelClaseUtil);

        btnCerrar.setMnemonic('C');
        btnCerrar.setText("Cerrar");
        btnCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarActionPerformed(evt);
            }
        });

        btnCopiar.setMnemonic('p');
        btnCopiar.setText("Copiar al portapapeles");
        btnCopiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCopiarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tabbedPanelCodigoGenerado)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnCopiar, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnCerrar, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tabbedPanelCodigoGenerado)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCerrar)
                    .addComponent(btnCopiar))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarActionPerformed
        ocultar();
    }//GEN-LAST:event_btnCerrarActionPerformed

    private void btnCopiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCopiarActionPerformed
        copiarCodigoAlPortapales();
    }//GEN-LAST:event_btnCopiarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCerrar;
    private javax.swing.JButton btnCopiar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JPanel panelAccesoBd;
    private javax.swing.JPanel panelClaseRegistro;
    private javax.swing.JPanel panelClaseUtil;
    private javax.swing.JTextArea taAccesoBd;
    private javax.swing.JTextArea taAccesoRegistro;
    private javax.swing.JTextArea taClaseUtilidad;
    private javax.swing.JTabbedPane tabbedPanelCodigoGenerado;
    // End of variables declaration//GEN-END:variables

    
    /**
     * Genera el código a mostrar en el formulario.
     * El código generado es introducido en el formulario.
     */
    void generarCodigo() {
        
        // Código de la clase para el acceso a la base de datos
        GeneracionBd generacion_bd = new GeneracionBd(cnt);
        StringBuilder codigo_clase_bd = generacion_bd.generarClaseAccesoBd(cnt);
        this.taAccesoBd.setText(codigo_clase_bd.toString());
        
        // Código de la clase para el objeto que encapsula el registro
        GeneracionRegistro generacion_registro = new GeneracionRegistro(cnt);
        StringBuilder codigo_clase_registro = generacion_registro.generarClaseRegistro(cnt);
        this.taAccesoRegistro.setText(codigo_clase_registro.toString());
        
        // Código de la clase con utilidades para manipular los registros
        GeneracionUtilidad generacion_utilidad = new GeneracionUtilidad(cnt);
        StringBuilder codigo_clase_utilidad = generacion_utilidad.generarClaseUtilidad(cnt);
        this.taClaseUtilidad.setText(codigo_clase_utilidad.toString());

        
    }
    
    
    /**
     * Muestra el formulario.
     */
    void mostrar() {
        generarCodigo();
        this.setVisible(true);
    }

    
    /**
     * Oculta la ventana actual.
     */
    private void ocultar() {
        this.setVisible(false);
    }

    
    /**
     * Copia el código generado, que hay visible en el panel activo, al portapales.
     */
    private void copiarCodigoAlPortapales() {
        int tab = this.tabbedPanelCodigoGenerado.getSelectedIndex();
        
        String codigo = "";
        if (tab == TAB_ACCESO_BD) {
            codigo = taAccesoBd.getText();
        } else if (tab == TAB_CLASE_REGISTRO) {
            codigo = taAccesoRegistro.getText();
        } else if (tab == TAB_CLASE_UTILIDAD) {
            codigo = taClaseUtilidad.getText();
        }
                
        
        Clipboard clipboard = Toolkit.getDefaultToolkit ().getSystemClipboard ();
        StringSelection seleccion = new StringSelection (codigo);
        clipboard.setContents(seleccion, null);
    }

}
