/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package es.cajal.autocodigo.forms;

import es.cajal.autocodigo.Comun;
import es.cajal.autocodigo.Contenedor;
import es.cajal.autocodigo.Propiedades;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author pmpreciado
 */
public class FormOpciones extends javax.swing.JFrame {

    /** Referencia al objeto contenedor */
    Contenedor cnt;
    
    
    /** Atributos del formulario */
    public int formato_espacios_tab;
    public int formato_columna_comentarios;
    public int formato_ancho_linea_maximo;
    
    public String jb_ambito_identificadores;
    public boolean jb_generar_get;
    public boolean jb_generar_set;
    
    public String tag_author;
    public String tag_contenedor;
    public String tag_contenedor_desc;
    public String tag_objeto_secundario_bd;
    public String tag_objeto_secundario_bd_desc;
    public boolean tag_inc_contenedor_llamadas_bd;
    public String tag_excepcion_1_nombre;
    public String tag_excepcion_1_desc;
    public String tag_excepcion_2_nombre;
    public String tag_excepcion_2_desc;
    public String tag_imports_bd;
    public String tag_imports_registro;
    public String tag_imports_utilidad;
    public String tag_clase_extends_db;
    
    
    /** Propiedades inferidas a partir de los atributos del formulario */
    public String tag_contenedor_clase;
    public String tag_contenedor_nombre;
    public String tag_objeto_secundario_bd_clase;
    public String tag_objeto_secundario_bd_nombre;
    
    
    /**
     * Creates new form FormOpciones
     * 
     * @param cnt                               Referencia al objeto contenedor
     */
    public FormOpciones(Contenedor cnt) {
        this.cnt = cnt;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnAceptar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        cbJbAmbitoIdentificadores = new javax.swing.JComboBox();
        cbJbGenerarGet = new javax.swing.JCheckBox();
        cbJbGenerarSet = new javax.swing.JCheckBox();
        jPanel3 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        tfTagContenedor = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        tfTagObjetoSecundarioBd = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        tfTagExcepcion1Nombre = new javax.swing.JTextField();
        tfTagExcepcion1Desc = new javax.swing.JTextField();
        tfTagExcepcion2Nombre = new javax.swing.JTextField();
        tfTagExcepcion2Desc = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tpTagImportsBd = new javax.swing.JTextPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        tpTagImportsRegistro = new javax.swing.JTextPane();
        jLabel7 = new javax.swing.JLabel();
        tfTagClaseExtendsDb = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        tfTagContenedorDesc = new javax.swing.JTextField();
        tfTagObjetoSecundarioBdDesc = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        tfTagAuthor = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tpTagImportsUtilidad = new javax.swing.JTextPane();
        cbIncContenedorLlamadasBd = new javax.swing.JCheckBox();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        tfFormatoEspaciosTab = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        tfFormatoColumnaComentarios = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        tfFormatoAnchoLineaMaximo = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Opciones");
        setResizable(false);

        btnAceptar.setText("Aceptar");
        btnAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAceptarActionPerformed(evt);
            }
        });

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Opciones"));

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Java Beans"));

        jLabel4.setText("Ámbito de los identificadores:");

        cbJbAmbitoIdentificadores.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "<ninguno>", "public", "protected", "private" }));

        cbJbGenerarGet.setText("Generar métodos get");
        cbJbGenerarGet.setToolTipText("");

        cbJbGenerarSet.setText("Generar métodos set");
        cbJbGenerarSet.setToolTipText("");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addComponent(cbJbAmbitoIdentificadores, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(cbJbGenerarGet)
                        .addGap(18, 18, 18)
                        .addComponent(cbJbGenerarSet)))
                .addContainerGap(582, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(cbJbAmbitoIdentificadores, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbJbGenerarGet)
                    .addComponent(cbJbGenerarSet))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Tags"));

        jLabel5.setText("Clase y nombre objeto contenedor:");

        jLabel6.setText("Nombre clase excepción 1:");

        jLabel8.setText("Nombre clase excepción 2:");

        jLabel9.setText("Descripción:");

        jLabel10.setText("Descripción:");

        jLabel11.setText("Clase y nombre objeto secundario para métodos de acceso a BD:");

        jLabel12.setText("Imports clase registro:");

        jLabel13.setText("Imports clase acceso BD:");

        jScrollPane1.setViewportView(tpTagImportsBd);

        jScrollPane2.setViewportView(tpTagImportsRegistro);

        jLabel7.setText("Nombre de la clase de la que extiende la clase BD:");

        jLabel14.setText("Descripción:");

        jLabel15.setText("Descripción:");

        jLabel16.setText("Autor:");

        jLabel17.setText("Imports clase utilidad:");

        jScrollPane3.setViewportView(tpTagImportsUtilidad);

        cbIncContenedorLlamadasBd.setText("Incluir objeto contenedor en llamadas a funciones de BD");
        cbIncContenedorLlamadasBd.setToolTipText("");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel11)
                                    .addComponent(jLabel5))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tfTagObjetoSecundarioBd, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tfTagContenedor, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel15)
                                    .addComponent(jLabel14))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tfTagContenedorDesc)
                                    .addComponent(tfTagObjetoSecundarioBdDesc)))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel16)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(tfTagAuthor, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 662, Short.MAX_VALUE)))
                        .addContainerGap())
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(jLabel7)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(tfTagClaseExtendsDb, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(407, 407, 407))
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel13)
                                            .addGroup(jPanel3Layout.createSequentialGroup()
                                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                                        .addComponent(jLabel12)
                                                        .addGap(127, 127, 127)
                                                        .addComponent(jLabel17))
                                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addGap(18, 18, 18)
                                                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                                        .addGap(110, 110, 110))
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(jLabel8)
                                        .addGap(18, 18, 18)
                                        .addComponent(tfTagExcepcion2Nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel10)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(tfTagExcepcion2Desc, javax.swing.GroupLayout.PREFERRED_SIZE, 425, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(jLabel6)
                                        .addGap(18, 18, 18)
                                        .addComponent(tfTagExcepcion1Nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(86, 86, 86)
                                        .addComponent(tfTagExcepcion1Desc, javax.swing.GroupLayout.PREFERRED_SIZE, 425, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel9))
                            .addComponent(cbIncContenedorLlamadasBd))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(tfTagAuthor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(tfTagContenedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14)
                    .addComponent(tfTagContenedorDesc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(tfTagObjetoSecundarioBd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15)
                    .addComponent(tfTagObjetoSecundarioBdDesc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cbIncContenedorLlamadasBd)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel9)
                        .addGap(213, 213, 213))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(tfTagExcepcion1Nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfTagExcepcion1Desc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(tfTagExcepcion2Desc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10)
                            .addComponent(tfTagExcepcion2Nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel13)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel12)
                                    .addComponent(jLabel17))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(tfTagClaseExtendsDb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(28, Short.MAX_VALUE))))
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Formato"));

        jLabel1.setText("Espacios por tabulación:");

        jLabel2.setText("Columna comentarios:");

        jLabel3.setText("Ancho de línea máximo:");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addGap(44, 44, 44)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tfFormatoAnchoLineaMaximo, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfFormatoColumnaComentarios, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfFormatoEspaciosTab, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(tfFormatoEspaciosTab, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfFormatoColumnaComentarios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfFormatoAnchoLineaMaximo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnAceptar, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAceptar)
                    .addComponent(btnCancelar))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        cancelar();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptarActionPerformed
        aceptar();
    }//GEN-LAST:event_btnAceptarActionPerformed

//    /**
//     * @param args the command line arguments
//     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(FormOpciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(FormOpciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(FormOpciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(FormOpciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new FormOpciones().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAceptar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JCheckBox cbIncContenedorLlamadasBd;
    private javax.swing.JComboBox cbJbAmbitoIdentificadores;
    private javax.swing.JCheckBox cbJbGenerarGet;
    private javax.swing.JCheckBox cbJbGenerarSet;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextField tfFormatoAnchoLineaMaximo;
    private javax.swing.JTextField tfFormatoColumnaComentarios;
    private javax.swing.JTextField tfFormatoEspaciosTab;
    private javax.swing.JTextField tfTagAuthor;
    private javax.swing.JTextField tfTagClaseExtendsDb;
    private javax.swing.JTextField tfTagContenedor;
    private javax.swing.JTextField tfTagContenedorDesc;
    private javax.swing.JTextField tfTagExcepcion1Desc;
    private javax.swing.JTextField tfTagExcepcion1Nombre;
    private javax.swing.JTextField tfTagExcepcion2Desc;
    private javax.swing.JTextField tfTagExcepcion2Nombre;
    private javax.swing.JTextField tfTagObjetoSecundarioBd;
    private javax.swing.JTextField tfTagObjetoSecundarioBdDesc;
    private javax.swing.JTextPane tpTagImportsBd;
    private javax.swing.JTextPane tpTagImportsRegistro;
    private javax.swing.JTextPane tpTagImportsUtilidad;
    // End of variables declaration//GEN-END:variables

    
    /**
     * Carga las opciones del formulario a partir del fichero de propiedades.
     * 
     * @param propiedades                       Fichero de propiedades
     */
    public void propiedades2Atributos(Propiedades propiedades) {
        
        /** Formato */
        formato_espacios_tab            = propiedades.prop_formato_espacios_tab;
        formato_columna_comentarios     = propiedades.prop_formato_columna_comentarios;
        formato_ancho_linea_maximo      = propiedades.prop_formato_ancho_linea_maximo;
        
        /** Java Beans */
        jb_ambito_identificadores       = propiedades.prop_jb_ambito_identificadores;
        jb_generar_get                  = propiedades.prop_jb_generar_get;
        jb_generar_set                  = propiedades.prop_jb_generar_set;

        /** Tags */
        tag_author                      = propiedades.prop_tag_author;
        tag_contenedor                  = propiedades.prop_tag_contenedor;
        tag_contenedor_desc             = propiedades.prop_tag_contenedor_desc;
        tag_objeto_secundario_bd        = propiedades.prop_tag_objeto_secundario_bd;
        tag_objeto_secundario_bd_desc   = propiedades.prop_tag_objeto_secundario_bd_desc;
        tag_inc_contenedor_llamadas_bd  = propiedades.prop_tag_tag_inc_contenedor_llamadas_bd;
        tag_excepcion_1_nombre          = propiedades.prop_tag_excepcion_1_nombre;
        tag_excepcion_1_desc            = propiedades.prop_tag_excepcion_1_desc;
        tag_excepcion_2_nombre          = propiedades.prop_tag_excepcion_2_nombre;
        tag_excepcion_2_desc            = propiedades.prop_tag_excepcion_2_desc;
        tag_imports_bd                  = propiedades.prop_tag_imports_bd;
        tag_imports_registro            = propiedades.prop_tag_imports_registro;
        tag_imports_utilidad            = propiedades.prop_tag_imports_utilidad;
        tag_clase_extends_db            = propiedades.prop_tag_clase_extends_db;
        
        atributos2Form();
        inferirAtributosIndirectos();
    }
    
    
    
    /**
     * Carga el formulario con los atributos de la clase.
     */
    void atributos2Form() {
        
        /** Formato */
        String s_prop_formato_tab = Integer.toString(formato_espacios_tab);
        String s_prop_formato_columna_comentarios = Integer.toString(formato_columna_comentarios);
        String s_prop_formato_ancho_linea_maximo = Integer.toString(formato_ancho_linea_maximo);
        tfFormatoEspaciosTab.setText(s_prop_formato_tab);
        tfFormatoColumnaComentarios.setText(s_prop_formato_columna_comentarios);
        tfFormatoAnchoLineaMaximo.setText(s_prop_formato_ancho_linea_maximo);
        
        /** Java Beans */
        cbJbAmbitoIdentificadores.setSelectedItem(jb_ambito_identificadores);
        cbJbGenerarGet.setSelected(jb_generar_get);
        cbJbGenerarSet.setSelected(jb_generar_set);
        
        /** Tags */
        this.tfTagAuthor.setText(tag_author);
        this.tfTagContenedor.setText(tag_contenedor);
        this.tfTagContenedorDesc.setText(tag_contenedor_desc);
        this.tfTagObjetoSecundarioBd.setText(tag_objeto_secundario_bd);
        this.tfTagObjetoSecundarioBdDesc.setText(tag_objeto_secundario_bd_desc);
        this.cbIncContenedorLlamadasBd.setSelected(tag_inc_contenedor_llamadas_bd);
        this.tfTagExcepcion1Nombre.setText(tag_excepcion_1_nombre);
        this.tfTagExcepcion1Desc.setText(tag_excepcion_1_desc);
        this.tfTagExcepcion1Nombre.setText(tag_excepcion_1_nombre);
        this.tfTagExcepcion1Desc.setText(tag_excepcion_1_desc);
        this.tpTagImportsBd.setText(tag_imports_bd);
        this.tpTagImportsRegistro.setText(tag_imports_registro);
        this.tpTagImportsUtilidad.setText(tag_imports_utilidad);
        this.tfTagClaseExtendsDb.setText(tag_clase_extends_db);
    }
    
    
    /**
     * Carga los atributos de la clase a partir de la información del formulario.
     */
    void form2Atributos() {
        
        /** Formato */
        formato_espacios_tab = Comun.toEntero(tfFormatoEspaciosTab.getText(), 4);
        formato_columna_comentarios = Comun.toEntero(tfFormatoColumnaComentarios.getText(), 49);
        formato_ancho_linea_maximo = Comun.toEntero(tfFormatoAnchoLineaMaximo.getText(), 120);
        
        /** Java Beans */
        jb_ambito_identificadores = cbJbAmbitoIdentificadores.getSelectedItem().toString();
        jb_generar_get = cbJbGenerarGet.isSelected();
        jb_generar_set = cbJbGenerarSet.isSelected();
        
        /** Tags */
        tag_author = tfTagAuthor.getText();
        tag_contenedor = tfTagContenedor.getText();
        tag_contenedor_desc = tfTagContenedorDesc.getText();
        tag_objeto_secundario_bd = tfTagObjetoSecundarioBd.getText();
        tag_objeto_secundario_bd_desc = tfTagObjetoSecundarioBdDesc.getText();
        tag_inc_contenedor_llamadas_bd = cbIncContenedorLlamadasBd.isSelected();
        tag_excepcion_1_nombre = tfTagExcepcion1Nombre.getText();
        tag_excepcion_1_desc = tfTagExcepcion1Desc.getText();
        tag_excepcion_2_nombre = tfTagExcepcion2Nombre.getText();
        tag_excepcion_2_desc = tfTagExcepcion2Desc.getText();
        tag_imports_bd = tpTagImportsBd.getText();
        tag_imports_registro = tpTagImportsRegistro.getText();
        tag_imports_utilidad = tpTagImportsUtilidad.getText();
        tag_clase_extends_db = tfTagClaseExtendsDb.getText();
        
        inferirAtributosIndirectos();
    }
    
    
    /**
     * Comprueba que, si el usuario ha especificado el tag del objeto contenedor, este conste de dos elementos: clase y nombre del objeto.
     * En caso de que no, muestra un mensaje de aviso y retorna 'false'.
     * 
     * @return                                  'true' si la comprobación ha sido correcta
     *                                          'false' si ha sido errónea
     */
    private boolean checkTagContenedor() {
        if (Comun.vacio(tag_contenedor)) {
            return true;
        }
        
        List <String> l_items_contenedor = Comun.split(tag_contenedor, " ");
        if (l_items_contenedor.size() != 2) {
            String mensaje = "El campo \"Clase y nombre objeto contenedor\" debe constar de dos elementos";
            es.cajal.autocodigo.Dialogos.showMessageDialog(cnt, this, mensaje, "Error", JOptionPane.ERROR_MESSAGE);
            
            return false;
        }
        
        return true;
    }
    

    /**
     * Establece el valor de los atributos indirectos a partir de los atributos introducidos en el formulario.
     * Si detecta algún error, muestra un mensaje al usuario.
     */
    private void inferirAtributosIndirectos() {
        
        // Objeto contenedor
        List <String> l_items_contenedor = Comun.split(tag_contenedor, " ");
        if (l_items_contenedor.size() != 2) {
            this.tag_contenedor_clase = null;
            this.tag_contenedor_nombre = null;
            
        } else {
            this.tag_contenedor_clase = l_items_contenedor.get(0);
            this.tag_contenedor_nombre = l_items_contenedor.get(1);
        }
        
        // Objeto secundario
        if (Comun.vacio(tag_objeto_secundario_bd)) {
            this.tag_objeto_secundario_bd_clase = null;
            this.tag_objeto_secundario_bd_nombre = null;
        } else {
            List <String> l_items_objeto_secundario = Comun.split(tag_objeto_secundario_bd, " ");
            if (l_items_objeto_secundario.size() != 2) {
                String mensaje = "Si se utiliza el campo \"Clase y nombre objeto secundario\", debe constar de dos elementos";
                es.cajal.autocodigo.Dialogos.showMessageDialog(cnt, this, mensaje, "Error", JOptionPane.ERROR_MESSAGE);

                this.tag_objeto_secundario_bd_clase = null;
                this.tag_objeto_secundario_bd_nombre = null;

            } else {
                this.tag_objeto_secundario_bd_clase = l_items_objeto_secundario.get(0);
                this.tag_objeto_secundario_bd_nombre = l_items_objeto_secundario.get(1);
            }
        }
    }
    
    
    
    /**
     * Muestra el formulario.
     */
    void mostrar() {
        this.setVisible(true);
    }

    
    /**
     * Sale del formulario sin guardar los cambios.
     */
    private void cancelar() {
        atributos2Form();
        this.setVisible(false);
    }

    
    /**
     * Sale del formulario guardando los cambios.
     */    
    private void aceptar() {
        boolean ok_tag_contenedor = checkTagContenedor();
        if (ok_tag_contenedor) {
            form2Atributos();
            this.setVisible(false);
        }
    }
}
